#app:
  #datasource:
    #jdbc-url: jdbc:postgresql://localhost:5432/prac1db
    #username: postgres
    #password: password
    #pool-size: 30

spring.datasource.jdbcUrl=${SPR_DATASOURCE_URL}
spring.datasource.driverClassName=${SPR_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.username=${SPR_DATASOURCE_USERNAME}
spring.datasource.password=${SPR_DATASOURCE_PASSWORD}

#spring:
#  datasource:
#    jdbcUrl:
#    username:
#    password:



#server:
#  port: 8081